[project]
name = "diskstore"
version = "0.6.0"
description = "Simple MutableMapping compatible SQLite based disk storage."
readme = "README.md"
license = "BSD-3-Clause"
license-files = ["LICENSE.txt"]
requires-python = ">=3.10"
authors = [{ name = "tds333", email = "tds333@mailbox.org" }]
keywords = [
  "sqlite",
  "diskstore",
  "disk",
  "storage",
  "cache",
  "key-value",
  "kv",
  "database",
  "mutablemapping",
  "apsw",
  "pydantic",
  "dataclasses",
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
  "Programming Language :: Python :: Implementation :: CPython",
  "Topic :: Database",
  "Topic :: Database :: Database Engines/Servers",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: System :: Filesystems",
  "Typing :: Typed",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/tds333/diskstore"
Documentation = "https://tds333.github.io/diskstore/"
Source = "https://github.com/tds333/diskstore"
Changelog = "https://github.com/tds333/diskstore/blob/main/docs/CHANGELOG.md"
Issues = "https://github.com/tds333/diskstore/issues"
CI = "https://github.com/tds333/diskstore/actions"

[project.optional-dependencies]
apsw = ["apsw>=3.51.3"]

[dependency-groups]
dev = [
  "apsw>=3.51.3",
  "msgspec>=0.20.0",
  "pydantic>=2.12.5,<=2.99.99b0",
  "pytest",
  "pytest-asyncio>=1.3.0",
  "pytest-cov",
  "pytest-examples>=0.0.18",
  "pytest-xdist",
  "structtype>=0.8.1",
]
docs = [
  "mkdocstrings[python]>=1.0.3",
  "zensical>=0.0.23",
]

[build-system]
requires = ["uv_build>=0.9.2,<1"]
build-backend = "uv_build"

[tool.coverage.run]
parallel = true
branch = true
source = ["diskstore"]

[tool.coverage.report]
show_missing = true
skip_covered = true
exclude_lines = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]

[tool.pytest]
# pythonpath = ["src"]
testpaths = ["tests"]

[tool.ruff]
exclude = [".env", ".venv", "venv"]
line-length = 88

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "W",  # pycodestyle warnings
  "F",  # pyflakes
  "I",  # isort
  "C",  # flake8-comprehensions
  "B",  # flake8-bugbear
  "PT",  # flake8-pytest
  "N",  # naming
  # "D",  # docu
  "PL",  # pylint
  "RUF",  # ruff
]
ignore = [
  # "E501", # line too long, handled by black
  "B008",  # do not perform function calls in argument defaults
  "C901",  # too complex
  "RET504",
  "PLR2004",
]

[tool.uv]
#exclude-newer = "1 days"
